//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.14 at 11:20:14 PM EET 
//


package org.d11.admin.jaxb.match;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Goal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Goal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{http://match.jaxb.tools.dromelvan.org}Player"/>
 *         &lt;element name="team" type="{http://match.jaxb.tools.dromelvan.org}Team"/>
 *         &lt;element name="time" type="{http://match.jaxb.tools.dromelvan.org}time"/>
 *         &lt;element name="penalty" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ownGoal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Goal", propOrder = {
    "player",
    "team",
    "time",
    "penalty",
    "ownGoal"
})
public class Goal {

    @XmlElement(required = true)
    protected Player player;
    @XmlElement(required = true)
    protected Team team;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int time;
    protected boolean penalty;
    protected boolean ownGoal;

    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link Player }
     *     
     */
    public Player getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link Player }
     *     
     */
    public void setPlayer(Player value) {
        this.player = value;
    }

    /**
     * Gets the value of the team property.
     * 
     * @return
     *     possible object is
     *     {@link Team }
     *     
     */
    public Team getTeam() {
        return team;
    }

    /**
     * Sets the value of the team property.
     * 
     * @param value
     *     allowed object is
     *     {@link Team }
     *     
     */
    public void setTeam(Team value) {
        this.team = value;
    }

    /**
     * Gets the value of the time property.
     * 
     */
    public int getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     */
    public void setTime(int value) {
        this.time = value;
    }

    /**
     * Gets the value of the penalty property.
     * 
     */
    public boolean isPenalty() {
        return penalty;
    }

    /**
     * Sets the value of the penalty property.
     * 
     */
    public void setPenalty(boolean value) {
        this.penalty = value;
    }

    /**
     * Gets the value of the ownGoal property.
     * 
     */
    public boolean isOwnGoal() {
        return ownGoal;
    }

    /**
     * Sets the value of the ownGoal property.
     * 
     */
    public void setOwnGoal(boolean value) {
        this.ownGoal = value;
    }

}
