//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.14 at 11:20:14 PM EET 
//


package org.d11.admin.jaxb.match;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Match complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Match">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="whoScoredId" type="{http://match.jaxb.tools.dromelvan.org}whoScoredId"/>
 *         &lt;element name="dateTime" type="{http://match.jaxb.tools.dromelvan.org}dateTime"/>
 *         &lt;element name="timeElapsed" type="{http://match.jaxb.tools.dromelvan.org}timeElapsed"/>
 *         &lt;element name="teams" type="{http://match.jaxb.tools.dromelvan.org}Teams"/>
 *         &lt;element name="playerMatchStats" type="{http://match.jaxb.tools.dromelvan.org}PlayerMatchStats"/>
 *         &lt;element name="goals" type="{http://match.jaxb.tools.dromelvan.org}Goals"/>
 *         &lt;element name="cards" type="{http://match.jaxb.tools.dromelvan.org}Cards"/>
 *         &lt;element name="substitutions" type="{http://match.jaxb.tools.dromelvan.org}Substitutions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Match", propOrder = {
    "whoScoredId",
    "dateTime",
    "timeElapsed",
    "teams",
    "playerMatchStats",
    "goals",
    "cards",
    "substitutions"
})
public class Match {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger whoScoredId;
    @XmlElement(required = true)
    protected String dateTime;
    @XmlElement(required = true)
    protected String timeElapsed;
    @XmlElement(required = true)
    protected Teams teams;
    @XmlElement(required = true)
    protected PlayerMatchStats playerMatchStats;
    @XmlElement(required = true)
    protected Goals goals;
    @XmlElement(required = true)
    protected Cards cards;
    @XmlElement(required = true)
    protected Substitutions substitutions;

    /**
     * Gets the value of the whoScoredId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWhoScoredId() {
        return whoScoredId;
    }

    /**
     * Sets the value of the whoScoredId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWhoScoredId(BigInteger value) {
        this.whoScoredId = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the timeElapsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeElapsed() {
        return timeElapsed;
    }

    /**
     * Sets the value of the timeElapsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeElapsed(String value) {
        this.timeElapsed = value;
    }

    /**
     * Gets the value of the teams property.
     * 
     * @return
     *     possible object is
     *     {@link Teams }
     *     
     */
    public Teams getTeams() {
        return teams;
    }

    /**
     * Sets the value of the teams property.
     * 
     * @param value
     *     allowed object is
     *     {@link Teams }
     *     
     */
    public void setTeams(Teams value) {
        this.teams = value;
    }

    /**
     * Gets the value of the playerMatchStats property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerMatchStats }
     *     
     */
    public PlayerMatchStats getPlayerMatchStats() {
        return playerMatchStats;
    }

    /**
     * Sets the value of the playerMatchStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerMatchStats }
     *     
     */
    public void setPlayerMatchStats(PlayerMatchStats value) {
        this.playerMatchStats = value;
    }

    /**
     * Gets the value of the goals property.
     * 
     * @return
     *     possible object is
     *     {@link Goals }
     *     
     */
    public Goals getGoals() {
        return goals;
    }

    /**
     * Sets the value of the goals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Goals }
     *     
     */
    public void setGoals(Goals value) {
        this.goals = value;
    }

    /**
     * Gets the value of the cards property.
     * 
     * @return
     *     possible object is
     *     {@link Cards }
     *     
     */
    public Cards getCards() {
        return cards;
    }

    /**
     * Sets the value of the cards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cards }
     *     
     */
    public void setCards(Cards value) {
        this.cards = value;
    }

    /**
     * Gets the value of the substitutions property.
     * 
     * @return
     *     possible object is
     *     {@link Substitutions }
     *     
     */
    public Substitutions getSubstitutions() {
        return substitutions;
    }

    /**
     * Sets the value of the substitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Substitutions }
     *     
     */
    public void setSubstitutions(Substitutions value) {
        this.substitutions = value;
    }

}
