//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.14 at 11:20:14 PM EET 
//


package org.d11.admin.jaxb.match;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.d11.admin.jaxb.match package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Match_QNAME = new QName("http://match.jaxb.tools.dromelvan.org", "match");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.d11.admin.jaxb.match
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link PlayerMatchStat }
     * 
     */
    public PlayerMatchStat createPlayerMatchStat() {
        return new PlayerMatchStat();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link Card }
     * 
     */
    public Card createCard() {
        return new Card();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link Substitution }
     * 
     */
    public Substitution createSubstitution() {
        return new Substitution();
    }

    /**
     * Create an instance of {@link Substitutions }
     * 
     */
    public Substitutions createSubstitutions() {
        return new Substitutions();
    }

    /**
     * Create an instance of {@link Teams }
     * 
     */
    public Teams createTeams() {
        return new Teams();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link PlayerMatchStats }
     * 
     */
    public PlayerMatchStats createPlayerMatchStats() {
        return new PlayerMatchStats();
    }

    /**
     * Create an instance of {@link Goals }
     * 
     */
    public Goals createGoals() {
        return new Goals();
    }

    /**
     * Create an instance of {@link Cards }
     * 
     */
    public Cards createCards() {
        return new Cards();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Match }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://match.jaxb.tools.dromelvan.org", name = "match")
    public JAXBElement<Match> createMatch(Match value) {
        return new JAXBElement<Match>(_Match_QNAME, Match.class, null, value);
    }

}
