//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.14 at 11:20:14 PM EET 
//


package org.d11.admin.jaxb.match;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlayerMatchStat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlayerMatchStat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{http://match.jaxb.tools.dromelvan.org}Player"/>
 *         &lt;element name="team" type="{http://match.jaxb.tools.dromelvan.org}Team"/>
 *         &lt;element name="lineup" type="{http://match.jaxb.tools.dromelvan.org}lineup"/>
 *         &lt;element name="substitutionOnTime" type="{http://match.jaxb.tools.dromelvan.org}time"/>
 *         &lt;element name="substitutionOffTime" type="{http://match.jaxb.tools.dromelvan.org}time"/>
 *         &lt;element name="goalsScored" type="{http://match.jaxb.tools.dromelvan.org}goalsScored"/>
 *         &lt;element name="goalAssists" type="{http://match.jaxb.tools.dromelvan.org}goalAssists"/>
 *         &lt;element name="ownGoals" type="{http://match.jaxb.tools.dromelvan.org}goalAssists"/>
 *         &lt;element name="goalsConceded" type="{http://match.jaxb.tools.dromelvan.org}goalsConceded"/>
 *         &lt;element name="yellowCardTime" type="{http://match.jaxb.tools.dromelvan.org}time"/>
 *         &lt;element name="redCardTime" type="{http://match.jaxb.tools.dromelvan.org}time"/>
 *         &lt;element name="manOfTheMatch" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sharedManOfTheMatch" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="rating" type="{http://match.jaxb.tools.dromelvan.org}rating"/>
 *         &lt;element name="playedPosition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="position" type="{http://match.jaxb.tools.dromelvan.org}position"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlayerMatchStat", propOrder = {
    "player",
    "team",
    "lineup",
    "substitutionOnTime",
    "substitutionOffTime",
    "goalsScored",
    "goalAssists",
    "ownGoals",
    "goalsConceded",
    "yellowCardTime",
    "redCardTime",
    "manOfTheMatch",
    "sharedManOfTheMatch",
    "rating",
    "playedPosition",
    "position"
})
public class PlayerMatchStat {

    @XmlElement(required = true)
    protected Player player;
    @XmlElement(required = true)
    protected Team team;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int lineup;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int substitutionOnTime;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int substitutionOffTime;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int goalsScored;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int goalAssists;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int ownGoals;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int goalsConceded;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int yellowCardTime;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int redCardTime;
    protected boolean manOfTheMatch;
    protected boolean sharedManOfTheMatch;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int rating;
    @XmlElement(required = true)
    protected String playedPosition;
    @XmlSchemaType(name = "positiveInteger")
    protected int position;

    /**
     * Gets the value of the player property.
     * 
     * @return
     *     possible object is
     *     {@link Player }
     *     
     */
    public Player getPlayer() {
        return player;
    }

    /**
     * Sets the value of the player property.
     * 
     * @param value
     *     allowed object is
     *     {@link Player }
     *     
     */
    public void setPlayer(Player value) {
        this.player = value;
    }

    /**
     * Gets the value of the team property.
     * 
     * @return
     *     possible object is
     *     {@link Team }
     *     
     */
    public Team getTeam() {
        return team;
    }

    /**
     * Sets the value of the team property.
     * 
     * @param value
     *     allowed object is
     *     {@link Team }
     *     
     */
    public void setTeam(Team value) {
        this.team = value;
    }

    /**
     * Gets the value of the lineup property.
     * 
     */
    public int getLineup() {
        return lineup;
    }

    /**
     * Sets the value of the lineup property.
     * 
     */
    public void setLineup(int value) {
        this.lineup = value;
    }

    /**
     * Gets the value of the substitutionOnTime property.
     * 
     */
    public int getSubstitutionOnTime() {
        return substitutionOnTime;
    }

    /**
     * Sets the value of the substitutionOnTime property.
     * 
     */
    public void setSubstitutionOnTime(int value) {
        this.substitutionOnTime = value;
    }

    /**
     * Gets the value of the substitutionOffTime property.
     * 
     */
    public int getSubstitutionOffTime() {
        return substitutionOffTime;
    }

    /**
     * Sets the value of the substitutionOffTime property.
     * 
     */
    public void setSubstitutionOffTime(int value) {
        this.substitutionOffTime = value;
    }

    /**
     * Gets the value of the goalsScored property.
     * 
     */
    public int getGoalsScored() {
        return goalsScored;
    }

    /**
     * Sets the value of the goalsScored property.
     * 
     */
    public void setGoalsScored(int value) {
        this.goalsScored = value;
    }

    /**
     * Gets the value of the goalAssists property.
     * 
     */
    public int getGoalAssists() {
        return goalAssists;
    }

    /**
     * Sets the value of the goalAssists property.
     * 
     */
    public void setGoalAssists(int value) {
        this.goalAssists = value;
    }

    /**
     * Gets the value of the ownGoals property.
     * 
     */
    public int getOwnGoals() {
        return ownGoals;
    }

    /**
     * Sets the value of the ownGoals property.
     * 
     */
    public void setOwnGoals(int value) {
        this.ownGoals = value;
    }

    /**
     * Gets the value of the goalsConceded property.
     * 
     */
    public int getGoalsConceded() {
        return goalsConceded;
    }

    /**
     * Sets the value of the goalsConceded property.
     * 
     */
    public void setGoalsConceded(int value) {
        this.goalsConceded = value;
    }

    /**
     * Gets the value of the yellowCardTime property.
     * 
     */
    public int getYellowCardTime() {
        return yellowCardTime;
    }

    /**
     * Sets the value of the yellowCardTime property.
     * 
     */
    public void setYellowCardTime(int value) {
        this.yellowCardTime = value;
    }

    /**
     * Gets the value of the redCardTime property.
     * 
     */
    public int getRedCardTime() {
        return redCardTime;
    }

    /**
     * Sets the value of the redCardTime property.
     * 
     */
    public void setRedCardTime(int value) {
        this.redCardTime = value;
    }

    /**
     * Gets the value of the manOfTheMatch property.
     * 
     */
    public boolean isManOfTheMatch() {
        return manOfTheMatch;
    }

    /**
     * Sets the value of the manOfTheMatch property.
     * 
     */
    public void setManOfTheMatch(boolean value) {
        this.manOfTheMatch = value;
    }

    /**
     * Gets the value of the sharedManOfTheMatch property.
     * 
     */
    public boolean isSharedManOfTheMatch() {
        return sharedManOfTheMatch;
    }

    /**
     * Sets the value of the sharedManOfTheMatch property.
     * 
     */
    public void setSharedManOfTheMatch(boolean value) {
        this.sharedManOfTheMatch = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     */
    public int getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(int value) {
        this.rating = value;
    }

    /**
     * Gets the value of the playedPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayedPosition() {
        return playedPosition;
    }

    /**
     * Sets the value of the playedPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayedPosition(String value) {
        this.playedPosition = value;
    }

    /**
     * Gets the value of the position property.
     * 
     */
    public int getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPosition(int value) {
        this.position = value;
    }

}
