#!/bin/bash
command=$1 
if [[ $command = "matchday" ]]
then
    match_day_number=$2
    if [[ -n "${match_day_number#"${match_day_number%%[![:space:]]*}"}" ]]
    then
        season=$3
        if [[ -n "${season#"${season%%[![:space:]]*}"}" ]]
        then
            java -cp 'lib/*:config' org.d11.admin.D11Admin $command -number $2 -season $3
        else
            java -cp 'lib/*:config' org.d11.admin.D11Admin $command -number $2
        fi
    else
        java -cp 'lib/*:config' org.d11.admin.D11Admin $command
    fi
elif [[ $command = "match" ]]
then
    match_id=$2
    previous=$3
    if [[ $previous = "false" ]]
    then
        java -cp 'lib/*:config' org.d11.admin.D11Admin -password $command -matchId $2
    else
        java -cp 'lib/*:config' org.d11.admin.D11Admin -password $command -matchId $2 -previous
    fi
elif [[ $command = "datetimes" ]]
then
    java -cp 'lib/*:config' org.d11.admin.D11Admin -password $command
else
    java -cp 'lib/*:config' org.d11.admin.D11Admin $command
fi
exit 0