#!/bin/bash
command=$1 
if [[ $command = "matchday" ]]
then
    match_day_number=$2
    if [[ -n "${match_day_number#"${match_day_number%%[![:space:]]*}"}" ]]
    then
        season=$3
        if [[ -n "${season#"${season%%[![:space:]]*}"}" ]]
        then
            java -cp 'lib/*:config' org.d11.admin.D11Admin $command -number $2 -season $3
        else
            java -cp 'lib/*:config' org.d11.admin.D11Admin $command -number $2
        fi
    else
        java -cp 'lib/*:config' org.d11.admin.D11Admin $command
    fi
elif [[ $command = "update" ]]
then
    shift
    match_ids=$@
    java -cp 'lib/*:config' org.d11.admin.D11Admin -password $command -matchIds "$match_ids"
elif [[ $command = "datetimes" ]]
then
    java -cp 'lib/*:config' org.d11.admin.D11Admin -password $command
else
    java -cp 'lib/*:config' org.d11.admin.D11Admin $command
fi
exit 0